const mails = [
 {id:1,sender:'Maya Chen',email:'maya@atelier.work',subject:'The revised project timeline',preview:'Hi Anika — I folded in the feedback from Friday and…',date:'10:42',unread:true,body:`Hi Anika,<br><br>I folded in the feedback from Friday and updated the milestones. The one point I’d love your eyes on is the research handoff in week three.<br><br>I’ve attached the revised timeline as a PDF. No rush — whenever you have a moment this week is perfect.<br><br>Warmly,<br>Maya`,file:'project-timeline-v3.pdf',size:'2.4 MB'},
 {id:2,sender:'Nikhil Rao',email:'nikhil@fieldnotes.org',subject:'Re: Summer residency notes',preview:'This is exactly the direction I was hoping for. The…',date:'Yesterday',unread:true,body:`This is exactly the direction I was hoping for. The material feels much more grounded now, especially the section on the coastal archive.<br><br>Let’s speak next week and shape the final outline.`,file:null},
 {id:3,sender:'The Lattice Review',email:'editors@latticereview.com',subject:'Your submission has been received',preview:'Thank you for submitting “Notes from a moving train”…',date:'Aug 13',unread:false,body:`Dear Anika,<br><br>Thank you for submitting “Notes from a moving train” to The Lattice Review. Our editorial team will be in touch after review.<br><br>Best,<br>Editorial team`,file:null},
 {id:4,sender:'Marta Ionescu',email:'marta@studioalto.io',subject:'Reference images for the workshop',preview:'A small selection from last month’s field visit.',date:'Aug 10',unread:false,body:`Hi Anika,<br><br>A small selection from last month’s field visit, as promised. Hope they help with the workshop framing.<br><br>Marta`,file:'field-visit.zip',size:'18.4 MB'}
];
let selected = 1, currentFolder='Inbox', compact=true, attached=false;
const $=s=>document.querySelector(s); const list=$('#messageList'), reader=$('#reader');
function renderList(items=mails){list.innerHTML=items.map(m=>`<div class="message ${m.unread?'unread':''} ${m.id===selected?'selected':''}" data-id="${m.id}"><div class="message-top"><span class="sender">${m.sender}</span><time>${m.date}</time></div><div class="subject">${m.subject}${m.file?'<span class="tag">attachment</span>':''}</div><div class="preview">${m.preview}</div></div>`).join('');document.querySelectorAll('.message').forEach(x=>x.onclick=()=>{selected=+x.dataset.id;const m=mails.find(q=>q.id===selected);m.unread=false;renderList();renderReader()})}
function renderReader(){const m=mails.find(x=>x.id===selected);if(!m){reader.innerHTML='<div class="reader-empty"><div><strong>Nothing selected</strong>Select a message to read it instantly.</div></div>';return}reader.innerHTML=`<div class="mail-actions"><div><button class="circle-action" title="Archive">⌑</button><button class="circle-action" title="Delete">⌫</button><button class="circle-action" title="Mark unread">●</button></div><div><button class="circle-action">↩</button><button class="circle-action">⋮</button></div></div><h2 class="mail-title">${m.subject}</h2><div class="sender-line"><span class="avatar">${m.sender.split(' ').map(x=>x[0]).join('')}</span><span><strong>${m.sender}</strong><small>to me · ${m.email}</small></span><time>${m.date}</time></div><div class="mail-body"><p>${m.body}</p>${m.file?`<div class="attachment"><span class="file-icon">▤</span><span><strong>${m.file}</strong><small>${m.size} · available locally</small></span><button>↓</button></div>`:''}</div>`}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');el.classList.add('show');setTimeout(()=>{el.classList.add('hidden');el.classList.remove('show')},3000)}
$('.compose').onclick=()=>$('#composerBackdrop').classList.remove('hidden');$('#closeComposer').onclick=()=>$('#composerBackdrop').classList.add('hidden');$('#minimizeBtn').onclick=()=>{ $('#composerBackdrop').classList.add('hidden');toast('Draft saved locally')};
$('#attachBtn').onclick=()=>{attached=true;$('#attachmentRow').innerHTML='<button id="attachBtn">⌇ Attach</button><span><b>research-notes.pdf</b> · 18.4 MB · uploading in background</span>';toast('Upload queued — it will resume if your connection changes')};
$('#networkBtn').onclick=()=>{compact=!compact;$('#netState').textContent=compact?'Compact mode':'Connection good';$('#netDetail').textContent=compact?'Saving data on this connection':'All content can sync normally';toast(compact?'Weak connection: prioritizing text and transfer progress':'Connection improved: syncing rich content')};
$('#refreshBtn').onclick=()=>{const s=$('#syncStatus');s.textContent='Syncing 2 new messages…';setTimeout(()=>s.textContent='Updated just now',1100)};
document.querySelectorAll('.folder').forEach(b=>b.onclick=()=>{document.querySelector('.folder.active').classList.remove('active');b.classList.add('active');currentFolder=b.dataset.folder;$('#folderTitle').textContent=currentFolder;$('#syncStatus').textContent=currentFolder==='Inbox'?'Updated just now':'Available offline';toast(`${currentFolder} opened from local mail cache`)});
$('#searchInput').oninput=e=>{const q=e.target.value.toLowerCase();renderList(mails.filter(m=>Object.values(m).join(' ').toLowerCase().includes(q)))};
function guard(){const to=$('#toInput').value,subject=$('#subjectInput').value,body=$('#bodyInput').value;let findings=[];const placeholders=/\[[^\]]*(?:name|university|topic|company)[^\]]*\]|\{[^}]+\}|<insert[^>]*>|(?:replace this|customize this|insert your|add professor)/ig;const hit=body.match(placeholders);if(hit)findings.push(`Template text: “${hit[0]}”`);if(/\b(attached|attachment|enclosed|please find)\b/i.test(body)&&!attached)findings.push('You mention an attachment, but none is attached.');if(!subject.trim())findings.push('Add a subject so your recipient knows what this is about.');if(to&&/prof\.patel/i.test(to)&&/dear professor sharma/i.test(body))findings.push('The greeting may not match your recipient.');return findings}
function queueSend(){const to=$('#toInput').value||'recipient';$('#guardBackdrop').classList.add('hidden');$('#composerBackdrop').classList.add('hidden');toast(`Saved locally — sending to ${to} in background`);$('#toInput').value='';$('#subjectInput').value='';$('#bodyInput').value='';attached=false;$('#attachmentRow').innerHTML='<button id="attachBtn">⌇ Attach</button><span>No attachment</span>';}
$('#sendBtn').onclick=()=>{const findings=guard();if(findings.length){$('#guardFindings').innerHTML=findings.map(x=>`<div class="finding">${x}</div>`).join('');$('#guardSummary').textContent=`${findings.length} thing${findings.length>1?'s':''} worth checking before this leaves your outbox.`;$('#guardBackdrop').classList.remove('hidden')}else queueSend()};$('#returnToDraft').onclick=()=>$('#guardBackdrop').classList.add('hidden');$('#sendAnyway').onclick=queueSend;
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')$('#sendBtn').click();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}});renderList();renderReader();
