import{put,all}from'./storage/indexeddb.js';import{levelFor,label}from'./pmr/index.js';import{ANC}from'./network/anc.js';import{UWTS}from'./scheduler/uwts.js';import{inspect}from'./sendguard/index.js';
const $=s=>document.querySelector(s),anc=new ANC(),scheduler=new UWTS();let folder='Inbox',selected,attachments=[],messages=[];const seed=[['m1','Inbox','Maya Chen','maya@atelier.work','The revised project timeline','Hi Anika,\n\nI folded in the feedback from Friday and updated the milestones. I’ve attached the revised timeline as a PDF.\n\nWarmly,\nMaya',false,false],['m2','Inbox','Nikhil Rao','nikhil@fieldnotes.org','Re: Summer residency notes','This is exactly the direction I was hoping for. The material feels much more grounded now.',false,true],['m3','Inbox','The Lattice Review','editors@latticereview.com','Your submission has been received','Dear Anika,\n\nThank you for submitting your work to The Lattice Review.',true,false]];
const esc=s=>String(s||'');const make=(tag,text,cls)=>{let n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n};const op=async(type,targetId,payload={})=>put('operations',{id:crypto.randomUUID(),type,targetId,payload,createdAt:Date.now(),status:'pending',attempts:0,idempotencyKey:crypto.randomUUID()});
async function save(m,operation){m.pmrLevel=levelFor(m);await put('messages',m);if(operation)await op(operation,m.id);render()}
function shown(){return messages.filter(m=>folder==='Starred'?m.starred:m.folder===folder)}
function render(){let list=$('#messageList');list.replaceChildren();shown().forEach(m=>{let row=make('button',null,`message ${!m.read?'unread':''} ${selected===m.id?'selected':''}`);row.type='button';let top=make('div',null,'message-top');top.append(make('span',m.sender,'sender'),make('time',new Date(m.timestamp).toLocaleDateString()));row.append(top,make('div',m.subject,'subject'),make('div',m.preview,'preview'));row.onclick=()=>{selected=m.id;m.read=true;save(m,'read')};list.append(row)});$('#folderTitle').textContent=folder;renderReader();$('#diagnostics').replaceChildren(...[['State',anc.state],['Chunk size',`${anc.chunkSize()/1024} KB`],['Outbox',String(scheduler.jobs.length)],['Messages',String(messages.length)]].flatMap(([a,b])=>[make('dt',a),make('dd',b)]))}
function renderReader(){let r=$('#reader'),m=messages.find(x=>x.id===selected);r.replaceChildren();if(!m){r.append(make('div','Select a message to read it instantly.','reader-empty'));return}let actions=make('div',null,'mail-actions'),left=make('div');[['⌑','Archive',()=>move(m,'Archive')],['⌫','Delete',()=>move(m,'Trash')],['☆','Star',()=>{m.starred=!m.starred;save(m,'star')}]].forEach(([t,l,f])=>{let b=make('button',t,'circle-action');b.title=l;b.onclick=f;left.append(b)});actions.append(left);r.append(actions,make('h2',m.subject,'mail-title'));let sender=make('div',null,'sender-line');sender.append(make('span',m.sender.split(' ').map(x=>x[0]).join(''),'avatar'),make('span',`${m.sender} · ${m.email}`));r.append(sender);let body=make('div',null,'mail-body');m.body.split('\n').forEach(line=>body.append(make('p',line)));body.append(make('small',label(m.pmrLevel)));r.append(body)}
async function move(m,to){m.folder=to;await save(m,'move')}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2500)}
let draftTimer;function draft(){clearTimeout(draftTimer);draftTimer=setTimeout(async()=>{let d={id:'active',to:$('#toInput').value,subject:$('#subjectInput').value,body:$('#bodyInput').value,attachments,updatedAt:Date.now()};await put('drafts',d);toast('Draft saved locally')},500)}
async function send(force=false){let d={to:$('#toInput').value,subject:$('#subjectInput').value,body:$('#bodyInput').value,attachments},g=inspect(d),warnings=Object.values(g).filter(Array.isArray).flat();if(warnings.length&&!force){let f=$('#guardFindings');f.replaceChildren(...warnings.map(x=>make('div',x.message,'finding')));$('#guardBackdrop').classList.remove('hidden');return}let m={id:crypto.randomUUID(),folder:'Sent',sender:'Anika Shah',email:'anika@mailosx.dev',recipients:[d.to],subject:d.subject||'(no subject)',body:d.body,timestamp:Date.now(),read:true,starred:false,attachments,preview:d.body.slice(0,90),syncState:'queued'};messages.push(m);await save(m,'send');scheduler.enqueue({kind:'outgoingTiny',id:m.id});$('#composerBackdrop').classList.add('hidden');toast('Saved locally — queued once with an idempotency key')}
async function boot(){messages=await all('messages');if(!messages.length){messages=seed.map(([id,folder,sender,email,subject,body,read,starred],i)=>({id,folder,sender,email,recipients:['anika@mailosx.dev'],subject,body,timestamp:Date.now()-(i+1)*864e5,read,starred,attachments:[],preview:body.slice(0,90),syncState:'synced',pmrLevel:2}));for(let m of messages)await put('messages',m)}let d=(await all('drafts')).find(x=>x.id==='active');if(d){$('#toInput').value=d.to;$('#subjectInput').value=d.subject;$('#bodyInput').value=d.body;attachments=d.attachments||[]}selected=messages[0]?.id;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
document.querySelectorAll('.folder').forEach(b=>b.onclick=()=>{document.querySelector('.folder.active').classList.remove('active');b.classList.add('active');folder=b.dataset.folder;render()});$('#composeBtn').onclick=()=>$('#composerBackdrop').classList.remove('hidden');$('#closeComposer').onclick=()=>$('#composerBackdrop').classList.add('hidden');['#toInput','#subjectInput','#bodyInput'].forEach(s=>$(s).addEventListener('input',draft));$('#attachmentInput').onchange=e=>{attachments=[...e.target.files].map(f=>({id:crypto.randomUUID(),name:f.name,size:f.size,available:true}));$('#attachmentStatus').textContent=attachments.map(a=>`${a.name} · ${(a.size/1048576).toFixed(1)} MB`).join(', ');draft();toast('Attachment metadata saved locally')};$('#sendBtn').onclick=()=>send();$('#sendAnyway').onclick=()=>send(true);$('#returnToDraft').onclick=()=>$('#guardBackdrop').classList.add('hidden');$('#networkBtn').onclick=()=>$('#debugPanel').classList.toggle('hidden');$('#closeDebug').onclick=()=>$('#debugPanel').classList.add('hidden');$('#networkProfile').onchange=e=>{anc.set(e.target.value);render();toast(`${anc.state}: useful work remains prioritized`)};$('#searchInput').oninput=e=>{let q=e.target.value.toLowerCase();let old=folder;folder='__search';let result=messages.filter(m=>[m.sender,m.email,m.subject,m.body,...m.attachments.map(a=>a.name)].join(' ').toLowerCase().includes(q));let list=$('#messageList');list.replaceChildren(...result.map(m=>make('div',`${m.sender} — ${m.subject}`,'message')));if(!q){folder=old;render()}};boot();
